version: "3.8"

# futtatas: redis + service
#   docker-compose -f docker-compose.develop.document-service-postgres.yml up --build --force-recreate
#
# belemaszas
#   docker run --rm -it docstore-document-service-postgresql:develop /bin/bash
services:

  doc-redis:
    extends:
      file: docker-compose.local.redis.yml
      service: redis

  doc-minio:
    extends:
      file: docker-compose.local.minio.yml
      service: doc-minio

  doc-document-service-developer:
    extends:
      file: docker-compose.local.document-service-postgres.yml
      service: doc-document-service-developer
    environment:
      LOGSTASH_ENABLED: false
      # 1GB
      UNDERTOW_HTTP_MAX_POST_SIZE: 1048576000
      # nagy fajlok feltoltesere kell csak ez a beallitas
      JAVA_OPTS: "-Xms200m -Xmx3000m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS -Djava.awt.headless=true"
    depends_on:
      doc-redis:
        condition: service_healthy
      doc-minio:
        condition: service_healthy

networks: 
  default: 
    external: true
    name: docstore-local-network
volumes:
  module-document-postgredb-data:
    name: module-document-postgredb-data
  doc_minio_data:
    name: doc-minio-data