# This workflow will generate html documentation from asciidoc and publish it to `gh-pages` branch
name: Deploy documentation
on:
  push:
    branches:
      - main
  #temporaly for testing
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      comment:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Comment for asciidoc generation'
        # Default value if no value is explicitly provided
        default: 'Generate asciidoc from SNAPSHOT'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch [main]
        uses: actions/checkout@v3
        with:
          ref: main

      # Includes the AsciiDoctor GitHub Pages Action to convert adoc files to html and publish to gh-pages branch
      - name: Generate with asciidoctor image
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          pdf_build: true
          asciidoctor_params: --attribute release_version=${CURRENT_VERSION}
          # adoc_file_ext: .ascii # default is .adoc
          source_dir: docs/ # default is .
          ebook_main_adoc_file: index
          # slides_build: true
          pre_build:
            CURRENT_VERSION=$(sed -rn 's/(^VERSION=)([^-]+)(-SNAPSHOT|)$/\2/p' .env)
            echo current version is ${CURRENT_VERSION}
            echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_OUTPUT
          # post_build:
